config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  root 'static_pages#home'

  get 'categories/show'

  get 'categories/new'

  get 'categories/create'
  
  get 'locations/new'
  
  get 'static_pages/home'
  
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get 'users/new'
  
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get    '/admin-login',   to: 'sessions#admin_new'
  post   '/admin-login',   to: 'sessions#admin_create'
  delete '/admin-logout',  to: 'sessions#admin_destroy'
  
  post 'messages/create', to: 'messages#create', as: 'create_message'
  
  post '/likes' => 'likeables#like', as: :like_create
  post '/dislikes' => 'likeables#dislike', as: :dislike_create
  post '/reset' => 'likeables#reset', as: :like_reset

  resources :users
  resources :courses
  resources :locations, except: :destroy
  resources :categories, except: :destroy

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :redirect_logged_in
  
  def home
  end
  
  private
  
    def redirect_logged_in
      if logged_in? || admin_logged_in?
        redirect_to courses_url
      end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div class="center jumbotron">
  <h1>Welcome to Your Course App</h1>
  <h2>
    This is the home page for RAD Assignment 2.
  </h2>
  <%= link_to signup_path, class: "btn btn-lg btn-danger" do %>
    <i class="fa fa-user-plus" aria-hidden="true"></i> Sign up now
  <% end %>
</div>

<div class="row" id="home-options">
  <div class="col-md-6">
    <h1>View all courses as a guest</h1>
    <p>Browse and view courses as a guest user</p>
    <%= link_to courses_path, class: "btn btn-success" do %>
      <i class="fa fa-book" aria-hidden="true"></i> Browse all courses
    <% end %>
  </div>
  <div class="col-md-6">
    <h1>Sign in to your account</h1>
    <p>Update your courses, view your courses, view coordinator information</p>
    <%= link_to login_path, class: "btn btn-success" do %>
      <i class="fa fa-sign-in" aria-hidden="true"></i> Log in to your account
    <% end %>
  </div>
</div>