config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  root 'static_pages#home'

  get 'categories/show'

  get 'categories/new'

  get 'categories/create'
  
  get 'locations/new'
  
  get 'static_pages/home'
  
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get 'users/new'
  
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get    '/admin-login',   to: 'sessions#admin_new'
  post   '/admin-login',   to: 'sessions#admin_create'
  delete '/admin-logout',  to: 'sessions#admin_destroy'
  
  post 'messages/create', to: 'messages#create', as: 'create_message'
  
  post '/likes' => 'likeables#like', as: :like_create
  post '/dislikes' => 'likeables#dislike', as: :dislike_create
  post '/reset' => 'likeables#reset', as: :like_reset

  resources :users
  resources :courses
  resources :locations, except: :destroy
  resources :categories, except: :destroy

end

app/models/likeable.rb
class Likeable < ApplicationRecord
  
  belongs_to :liked, class_name: "Course"
  belongs_to :liker, class_name: "User"
  validates :liked_id, presence: true
  validates :liker_id, presence: true
  
  # Create a like for course
  def self.create_like(course, current_user)
    like = Likeable.find_or_initialize_by(liker_id: current_user.id, liked_id: course.id)
    if like.like
      like.destroy
    else
      like.like= true
      like.save
    end
  end
  
  # Create a dislike for course
  def self.create_dislike(course, current_user)
    like = Likeable.find_or_initialize_by(liker_id: current_user.id, liked_id: course.id)
    if like.like == false
      like.destroy
    else
      like.like = false
      like.save
    end
  end
  
  def self.reset_likes(course)
    likes = Likeable.where(liked_id: course.id)
    likes.destroy_all
  end
    
end

app/controllers/likeables_controller.rb
class LikeablesController < ApplicationController
  before_action :logged_in_user, only: [:like, :dislike]
  before_action :set_course
  before_action :logged_in_admin, only: :reset
  
  def like
    Likeable.create_like(@course, current_user)
  end
  
  def dislike
    Likeable.create_dislike(@course, current_user)
  end
  
  def reset    
    if @course.likeables.any?
      Likeable.reset_likes(@course)
    end
  end
  
  private
  
    def set_course
      @course = Course.find(params[:id])
    end
  
end

app/helpers/likeables_helper.rb
module LikeablesHelper
end

app/views/likeables/_like.html.erb
<div id="like_course_<%= course.id %>">
  
  <li>
    <!-- Create dislike -->
    <%= link_to dislike_create_path(id: course.id), method: :post, remote: true do %>
      <i class="fa fa-thumbs-o-down" aria-hidden="true"></i> <%= count_dislikes(course) %>
    <% end %>
  </li>
  
  <li>
    <!-- Create like -->
    <%= link_to like_create_path(id: course.id), method: :post, remote: true do %>
      <i class="fa fa-thumbs-o-up" aria-hidden="true"></i> <%= count_likes(course) %>
    <% end %>
  </li>
  
</div>

app/views/likeables/_static_like.html.erb
<div id="like_course_<%= course.id %>">
  <li><i class="fa fa-thumbs-o-down" aria-hidden="true"></i> <%= count_dislikes(course) %></li>
  <li><i class="fa fa-thumbs-o-up" aria-hidden="true"></i> <%= count_likes(course) %></li>
</div>

app/views/likeables/dislike.js.erb
$("#like_course_<%= @course.id %>").html("<%= j(render partial: 'likeables/like', locals: {course: @course}) %>")

app/views/likeables/like.js.erb
$("#like_course_<%= @course.id %>").html("<%= j(render partial: 'likeables/like', locals: {course: @course}) %>")

app/views/likeables/reset.js.erb
$("#like_course_<%= @course.id %>").html("<%= j(render partial: 'likeables/static_like', locals: {course: @course}) %>")