config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  root 'static_pages#home'

  get 'categories/show'

  get 'categories/new'

  get 'categories/create'
  
  get 'locations/new'
  
  get 'static_pages/home'
  
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get 'users/new'
  
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get    '/admin-login',   to: 'sessions#admin_new'
  post   '/admin-login',   to: 'sessions#admin_create'
  delete '/admin-logout',  to: 'sessions#admin_destroy'
  
  post 'messages/create', to: 'messages#create', as: 'create_message'
  
  post '/likes' => 'likeables#like', as: :like_create
  post '/dislikes' => 'likeables#dislike', as: :dislike_create
  post '/reset' => 'likeables#reset', as: :like_reset

  resources :users
  resources :courses
  resources :locations, except: :destroy
  resources :categories, except: :destroy

end

app/models/course.rb
class Course < ApplicationRecord
  
  has_one :user
  
  has_many :locatables, dependent: :destroy
  has_many :locations, through: :locatables
  
  has_many :categorisations, dependent: :destroy
  has_many :categories, through: :categorisations
  
  has_many :likeables, foreign_key: "liked_id",
                       dependent:   :destroy
  has_many :likers, through: :likeables, source: :liker
  
  mount_uploader :picture, PictureUploader
  
  default_scope -> { order(created_at: :desc) }
  
  validates :user_id, presence: true
  validates :name, presence: true, length: { in: 10..50 },  uniqueness: { case_sensitive: false }
  validates :prerequisite, presence: true, length: { in: 10..50 }
  validates :description, presence: true, length: { in: 30..400 }
  validate :picture_size
  
  private
  
    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  
  before_action :set_course, only: [:edit, :update]
  before_action :logged_in_user, only: [:new, :create, :edit, :update]
  before_action :course_coordinator, only: [:edit, :update]
  before_action :logged_in_admin, only: [:destroy]
  
  # Course page
  def show
    @course = Course.find(params[:id])
    @user = User.find(@course.user_id)
    @categories = @course.categories
    @locations = @course.locations                  
  end
  
  # All courses page
  def index
    @courses = Course.all
    @users = User.find_by_sql("SELECT u.id, u.email, u.name FROM users AS u JOIN courses ON u.id = courses.user_id GROUP BY u.id")
  end
  
  # Create a course page
  def new
    @course = current_user.courses.build
  end
  
  # Create a course action
  def create
    @course = current_user.courses.build(course_params)
    if @course.save
      flash[:success] = "Course created!"
      redirect_to courses_url
    else
      render 'new'
    end
  end
  
  # Edit course page
  def edit
  end
  
  # Edit course action
  def update
    if @course.update_attributes(course_params)
      flash[:success] = "Course updated"
      redirect_to @course
    else
      render 'edit'
    end
  end
  
  
  def destroy
    Course.find(params[:id]).destroy
    flash[:success] = "Course deleted"
    redirect_back(fallback_location: courses_url)
  end
  
  
  private
    
    def course_params
      params.require(:course).permit(:name, :prerequisite, :description, :user_id, :picture, :category_ids => [], :location_ids => [])
    end
    
    # Sets course by getting id from params
    def set_course
      @course = Course.find(params[:id])
    end
    
    # Checks that current_user is course coordinator
    def course_coordinator
      @course = Course.find(params[:id])
      user = User.find(@course.user_id)
      if !current_user?(user)
        flash[:danger] = "You are not authorized to view that page."
        redirect_to courses_url
      end
    end
  
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<li>
  <div class="row">
      <div class="col-md-3">
        <% unless @hide_user %>
          <% @user = User.find(course.user_id) %>
          <%= render @user %>
        <% end %>
      </div>
    <div class="col-md-6 course">
      <div class="grey-box">
        <h2>
          <%= link_to course.name, course %>
        </h2>
        <p>
          <strong>Prequisite:</strong>
          <%= course.prerequisite %>
        </p>
        <% unless @hide_cat_loc %>
          <p>
            <strong>Category:</strong>
            <%= course.categories.map { |c| link_to(c.name, c) }.join(', ').html_safe %>
          </p>
          <p>
            <strong>Location: </strong>
            <%= course.locations.map { |l| link_to(l.location, l) }.join(', ').html_safe %>
          </p>
        <% end %>
        <p>
          <strong>Created: </strong>
          <%= time_ago_in_words(course.created_at) %> ago.
        </p>
        <% if admin_logged_in? %>
          <ul class="admin-btns">
            <li><%= link_to "Delete course", course, method: :delete,
                      data: { confirm: "Are you sure you want to delete #{course.name}?" }, class: "btn btn-danger" %></li>
            <li><%= link_to "Reset votes", like_reset_path(id: course.id), method: :post, class: "btn btn-warning", remote: true %></li>
          </ul>
        <% end %>
        <ul class="stats">
          <% if logged_in? %>
            <%= render partial: "likeables/like", locals: { course: course } %>
          <% else %>
            <%= render partial: "likeables/static_like", locals: { course: course } %>
          <% end %>
        </ul>
      </div>
    </div>
      <div class="col-md-3">
        <% unless @hide_picture %>
          <%= image_tag course.picture.thumb.url if course.picture? %>
        <% end %>
      </div>
  </div>
  <hr />
</li>

app/views/courses/_form.html.erb
    <div class="grey-box">
      <%= form_for @course do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
  
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
  
        <%= f.label :prerequisite %>
        <%= f.text_field :prerequisite, class: 'form-control' %>
  
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control', rows: '10' %>
        
        <%= f.label :category_ids, "Category" %>
        <div class="checkboxes">
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name, {}, { multiple: true } %>
        </div>
        
        <br />
        
        <%= f.label :location_ids, "Location" %>
        <div class="checkboxes">
          <%= f.collection_check_boxes :location_ids, Location.all, :id, :location, {}, { multiple: true } %>
        </div>
        
        <%= f.label :picture, "Course image" %>
        <span class="picture">
          <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
        </span>
  
        <%= f.submit yield(:button_text), class: "btn btn-success" %>
      <% end %>
    </div>

app/views/courses/edit.html.erb
<% provide(:title, "Edit course") %>
<% provide(:button_text, 'Update Course Information') %>
<h1>Edit course</h1>
<%= render 'form' %>

app/views/courses/index.html.erb
<% provide(:title, 'All Course') %>
<h1>All Courses</h1>
<hr />

<% if @courses.any? %>
  <div>
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#courses" aria-controls="courses" role="tab" data-toggle="tab">Courses</a></li>
      <li role="presentation"><a href="#coordinators" aria-controls="coordinators" role="tab" data-toggle="tab">Coordinators</a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane fade in active" id="courses">
        <ul class="courses">
          <%= render @courses %>
        </ul>
      </div>
      <div role="tabpanel" class="tab-pane fade" id="coordinators">
        <ul class="users-list">
          <%= render @users %>
        </ul>
      </div>
    </div>
  </div>
<% else %>
  <p class="center">No courses to show! :(</p>
<% end %>

<script>
  $('#myTabs a').click(function (e) {
    e.preventDefault()
    $(this).tab('show')
  })
</script>

app/views/courses/new.html.erb
<% provide(:title, 'Create a new course') %>
<% provide(:button_text, 'Create a new course') %>
<h1>Create a new course</h1>
<hr />
<%= render 'form' %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/courses/show.html.erb
<% provide(:title, @course.name) %>
<h1><%= @course.name%></h1>
<hr />
<div class="row">
  <div class="col-md-8">
    <div class="course">
      <h2>Prequisite: <%= @course.prerequisite %></h2>
      <div class="grey-box">
        <p>
          <strong>Category:</strong>
          <%= @categories.map { |c| link_to(c.name, c) }.join(', ').html_safe %>
        </p>
        <p>
          <strong>Location: </strong>
          <%= @locations.map { |l| link_to(l.location, l) }.join(', ').html_safe %>
        </p>
        <p><strong>Course description:</strong></p>
        <p><%= @course.description %></p>
        <%= image_tag @course.picture.url if @course.picture? %>
      </div>
    </div>
  </div>
  <div class="col-md-3 col-md-offset-1 course-user">
    <%= render @user %>
  </div>
</div>
<ul class="course-buttons">
  <li>
    <%= link_to "Return to Course List", courses_path, class: "btn btn-info" %>
  </li>
  <% if @user == current_user %>
    <li><%= link_to "Edit Course", edit_course_path(@course), class: "btn btn-success" %></li>
  <% end %>
  <% if admin_logged_in? %>
    <li><%= link_to "Delete course", "#", class: "btn btn-danger" %></li>
  <% end %>
</ul>