config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  root 'static_pages#home'

  get 'categories/show'

  get 'categories/new'

  get 'categories/create'
  
  get 'locations/new'
  
  get 'static_pages/home'
  
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get 'users/new'
  
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get    '/admin-login',   to: 'sessions#admin_new'
  post   '/admin-login',   to: 'sessions#admin_create'
  delete '/admin-logout',  to: 'sessions#admin_destroy'
  
  post 'messages/create', to: 'messages#create', as: 'create_message'
  
  post '/likes' => 'likeables#like', as: :like_create
  post '/dislikes' => 'likeables#dislike', as: :dislike_create
  post '/reset' => 'likeables#reset', as: :like_reset

  resources :users
  resources :courses
  resources :locations, except: :destroy
  resources :categories, except: :destroy

end

app/views/layouts/_footer.html.erb
<footer>
  <div class="row">
    <div class="center">
      <legend>Contact us</legend>
      <h5><%= mail_to "admin@sciencecourses.rmit.edu.au" %></h5>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <%= link_to "YOURCOURSE", root_path, id: "logo", class: "btn btn-lg btn-info" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        
        <!-- Category -->
        <li>
          <a href="#" class="dropdown-toggle btn btn-info" data-toggle="dropdown">
            <i class="fa fa-list-ol" aria-hidden="true"></i> Category <b class = "caret"></b>
          </a>
          <ul class="dropdown-menu">
            <% if Category.any? %>
              <% Category.all.each do |c| %>
                <li><%= link_to c.name, c %></li>
              <% end %>
            <% end %>
            <% if logged_in? %>
              <li class="divider"></li>
              <li>
                <%= link_to "Create Category", new_category_path %>
              </li>
            <% end %>
          </ul>
        </li>
        
        <!-- Location -->
        <li>
          <a href="#" class="dropdown-toggle btn btn-info" data-toggle="dropdown">
            <i class="fa fa-location-arrow" aria-hidden="true"></i> Location <b class = "caret"></b>
          </a>
          <ul class="dropdown-menu">
            <% if Location.any? %>
              <% Location.all.each do |l| %>
                <li><%= link_to l.location, l %></li>
              <% end %>
            <% end %>
            <% if logged_in? %>
              <li class="divider"></li>
              <li>
                <%= link_to "Create Location", new_location_path %>
              </li>
            <% end %>
          </ul>
        </li>
        
        <!-- Coordinator buttons -->
        <% if logged_in? %>
          <li>
            <%= link_to new_course_path, class: "btn btn-info" do %>
              <i class="fa fa-file-text-o" aria-hidden="true"></i> New Course
            <% end %>
          </li>
          <li>
            <a href="#" class="dropdown-toggle btn btn-danger" data-toggle="dropdown">
              <%= current_user.name %> <b class = "caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "View Profile", current_user %></li>
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% end %>
        
        <!-- Admin logout button -->
        <% if admin_logged_in? %>
          <li>
            <%= link_to users_path, class: "btn btn-info" do %>
                <i class="fa fa-users" aria-hidden="true"></i> Coordinators
              <% end %>
          </li>
          <li>
              <%= link_to admin_logout_path, method: "delete", class: "btn btn-info" do %>
                <i class="fa fa-sign-out" aria-hidden="true"></i> Log out
              <% end %>
          </li>
        <% end %>
        
        <!-- Login button -->
        <% if !logged_in? && !admin_logged_in? %>
          <li>
            <a href="#" class="dropdown-toggle btn btn-info" data-toggle="dropdown">
              <i class="fa fa-sign-in" aria-hidden="true"></i> Login <b class = "caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Coordinator Login", login_path %></li>
              <li><%= link_to "Admin Login", admin_login_path %></li>
            </ul>
          </li>
        <% end %>
        
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Your Course App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>

</body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= action_name.titleize %> :: <%= site_name %></title>
  <%= csrf_meta_tags %>
  <style>
    body {
        background: #fff;
        font-family: Helvetica, Arial, Sans-Serif;
        font-size: 14px;
    }

    .error_container {
        display: block;
        margin: auto;
        margin: 10% auto 0 auto;
        width: 40%;
    }
    .error_container .error {
        display: block; 
        text-align: center;
    }
    .error_container .error img {
        display: block;
        margin: 0 auto 25px auto;
    }
    .error_container .message strong {
        font-weight: bold;
        color: #f00;
    }
    .error_container .contact_info {
        display: block;
        text-align: center;
        margin: 25px 0 0 0;
    }
    .error_container .contact_info a {
        display: inline-block;
        margin: 0 5px;
        opacity: 0.4;
        transition: opacity 0.15s ease;
    }
    .error_container .contact_info a:hover {
        opacity: 0.8;
    }

  </style>
</head>
<body>

    <div class="error_container">
        <%= yield %>
    </div>

</body>
</html>